### ISSUE TITLE
Request for Code Release

### ISSUE THREAD

**Issue by rbsohee** [franciszzj/OpenPSG#1]
Hello, thank you for your interesting work on PSG! 
Could you please let me know when you plan on releasing the code? 

Thanks in advance! :)

**Comment by franciszzj** [comment]
Thank you very much for your attention to our work.
The code will be released in Sept. We are still in the process of refactoring, so stay tuned.

**Comment by franciszzj** [comment]
The code has been open sourced, thank you for your patience!
