### ISSUE TITLE
mask_features

### ISSUE THREAD

**Issue by Merak-Wang** [franciszzj/OpenPSG#4]
Thanks for your open-source work!
I tried to train the model by 
python -m torch.distributed.run \
  --nproc_per_node=2 \
  --master_port=27500 \
  tools/train.py \
  configs/psg/baseline_v4_ov.py \
  --auto-resume \
  --no-validate \
  --launcher pytorch
Error occured in openseed_relation_v2.py
line 107: ```openseed_outputs, mask_features = self.openseed.forward(batch_inputs)```

It seems that it did not in eval mode. After adding self.openseed.eval(), it can run.
Then, ValueError: not enough values to unpack (expected 2, got 1)
```self.openseed.forward(batch_inputs)``` return a list:
[{'sem_seg': tensor([[[0.1122, 0.1144, 0.1165,  ..., 0.0421, 0.0475, 0.0326],[0.1135, 0.... device='cuda:0', grad_fn=<ViewBackward0>), 'panoptic_seg': (...), 'instances': Instances(num_instances=86, image_height=360, image_width=640, fields=[pred_masks: te...19, 19, 19, 19],device='cuda:0')])}]

Are “mask_features" the visual feature output by the pixel decoder？
I directly cloned the official OpenSeeD code: https://github.com/IDEA-Research/OpenSeeD/

in openseed/architectures/openseed_model.py, class OpenSeeD
forward return ```processed_results = self.forward_seg(batched_inputs, task=inference_task)```

Sorry, I try to fix it, but I don't have more information. Perhaps I made a mistake somewhere? Could you please give me some advice?

**Comment by franciszzj** [comment]
Thanks for your interest in our work, please use https://github.com/franciszzj/OpenSeeD

**Comment by Merak-Wang** [comment]
> Thanks for your interest in our work, please use https://github.com/franciszzj/OpenSeeD

It works! Thanks for your generous sharing. By the way, except llama2, I’m currently training another LLMHead-Qwen1.5b and looking forward to its results!
